version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.1
  aws-ecs: circleci/aws-ecs@1.1.0
  aws-s3: circleci/aws-s3@1.0.11

# 実行環境の定義
executors:
  default:
    working_directory: ~/pictures_app
    docker:
      - image: circleci/node:10.7.0

# 実行コマンドの定義
commands:
  npm_install:
    steps:
      - run:
          name: Start npm install
          command: |
            cd client
            sudo apt-get install npm
            npm install

# ジョブの定義
jobs:
  vue_deploy:
    executor: default
    steps:
      - checkout
      - npm_install
      - run:
          name: build
          command: |
            cd client
            npm run build
      # - aws-s3/sync:
      #     from: client/dist
      #     to: s3:///
      #     overwrite: true

workflows:
  version: 2
  continuous-deploy:
    jobs:
      - vue_deploy:
          filters:
            branches:
              only: main_client
