Parameters:
  DBNameParameter:
    Type: String
  MasterUserParameter:
    Type: String
  MasterPasswordParameter:
    Type: String
    Description: "8文字以上で指定すること"

Resources:
  MyDBvideoInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DBNameParameter
      MasterUsername: !Ref MasterUserParameter
      MasterUserPassword: !Ref MasterPasswordParameter
      Engine: MySQL
      EnginVersion: 8.0
      DBInstanceClass: db.t2.micro
      StorageType: gp2
      PubliclyAccessible: True
      AllocatedStorage: "20"
      DBInstanceIdentifier: !Join ["-", ["MyDbInstance", !Ref "AWS::Region"]]
      AvailabilityZone: !Select [1, !GetAZs ""]
      DBSubnetGroupName: !Ref DBSubnetGroup

DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: プライベートサブネットを指定する
      SubnetIds:
        - !ImportValue 'Subnet1'
        - !ImportValue 'Subnet2'
